// Copyright (c) 2013 by Hyoung Bok Min, All rights reserved.
// For copyright information, refer to http://class.icc.skku.ac.kr/~min/program/license.html
var hanoi_js=!0,max_disks=10,canvash=200,towers=[],tpolew=6,tbasew=120,tbaseh=10,tbaseint=30,txpos=[100,250,400],def_dh=10,max_dh=15,def_dminw=22,def_dw=10,dh,dminw,dw,dint=2,th=0,trackGd=30,trackMin=100,trackw=2,tracktop=20,trackx1=[0,0,0],trackx2=[0,0,0],trackbx=0,trackby=0,trackex=0,trackey=0;
function createTowers(){if(1>ndisks||ndisks>max_disks)return alert("Number of disks should not exceed "+max_disks+" "),!1;dh=parseInt(def_dh*max_disks/ndisks);dh>max_dh&&(dh=max_dh);th=ndisks*(dh+dint);dminw=def_dminw;dw=def_dw;var a=parseInt(0.8*tbasew+0.5);if(4>ndisks){var b=parseInt(a/ndisks);b>dminw&&(dminw=b,1<ndisks&&(dw=parseInt((a-b)/(ndisks-1))))}else a>dminw+(ndisks-1)*dw&&(dw=parseInt((a-dminw)/(ndisks-1)));trackx1[0]=txpos[0]+tpolew+2*trackw;trackx2[0]=txpos[1]-tpolew-2*trackw;trackx1[1]=
trackx1[0];trackx2[1]=txpos[2]-tpolew-2*trackw;trackx1[2]=txpos[1]+tpolew+2*trackw;trackx2[2]=trackx2[1];tracktop=5<ndisks?0:20;towers[0]=[];towers[1]=[];towers[2]=[];a=towers[0];for(b=0;b<ndisks;b++)a[b]=ndisks-b;a=document.getElementById("titlenumdisks");a.innerHTML=ndisks;a=document.getElementById("titleto");a.innerHTML=to_tower;return!0}
function drawTowers(){var a=document.getElementById("myCanvas").getContext("2d");isIE8earlier()||(a.fillStyle="#000000",a.font="16px Arial",a.fillText("Tower 1",txpos[0]-30,canvash-10),a.fillText("Tower 2",txpos[1]-30,canvash-10),a.fillText("Tower 3",txpos[2]-30,canvash-10));a.fillStyle="#262626";var b=canvash-tbaseh-tbaseint,c=txpos[0]-tbasew/2;a.fillRect(c,b,tbasew,tbaseh);c=txpos[1]-tbasew/2;a.fillRect(c,b,tbasew,tbaseh);c=txpos[2]-tbasew/2;a.fillRect(c,b,tbasew,tbaseh);drawPoles(!0);drawDisks(!0)}
function drawPoles(a){var b=document.getElementById("myCanvas").getContext("2d");b.fillStyle=a?"#262626":"#FFFFFF";a=canvash-tbaseh-tbaseint;b.fillRect(txpos[0]-tpolew/2,a-th,tpolew,th);b.fillRect(txpos[1]-tpolew/2,a-th,tpolew,th);b.fillRect(txpos[2]-tpolew/2,a-th,tpolew,th)}
function drawDisks(a){var b=document.getElementById("myCanvas").getContext("2d");a||(b.fillStyle="#FFFFFF");for(var c=0;3>c;c++)for(var d=canvash-tbaseh-tbaseint-dh,f=towers[c],e=0;e<f.length;e++){var g=dminw+dw*(f[e]-1);a&&(b.fillStyle=f[e]%2?"#FF0000":"#0000FF");b.fillRect(txpos[c]-g/2,d,g,dh);d=d-dh-dint}}
function drawCurve(a,b,c,d,f){var e=document.getElementById("myCanvas").getContext("2d");e.beginPath();e.moveTo(b,c);a?(c=e.createLinearGradient(b,c,d,f),c.addColorStop("0","#11FF11"),c.addColorStop("0.5","#007400"),c.addColorStop("1.0","#003400"),e.strokeStyle=c,e.lineWidth=trackw):(e.strokeStyle="#FFFFFF",e.lineWidth=trackw+2);e.bezierCurveTo(b,tracktop,d,tracktop,d,f);e.stroke();a&&(e.strokeStyle="#003400");e.beginPath();e.moveTo(d,f);e.lineTo(d-2,f-10);e.stroke();e.beginPath();e.moveTo(d,f);e.lineTo(d+
2,f-10);e.stroke()}function drawTrack(a,b,c,d,f){0>=a&&0<trackbx&&(drawCurve(!1,trackbx,trackby,trackex,trackey),trackbx=trackby=trackex=trackey=0);drawCurve(!0,b,c,d,f);0<a?(setTimeout(function(){drawCurve(false,b,c,d,f)},a),trackbx=trackby=trackex=trackey=0):(trackbx=b,trackby=c,trackex=d,trackey=f)}function trackMode(){var a=document.getElementById("trackmode");a.innerHTML="O"==a.innerHTML?"X":"O"}var moveIndex=0,intervalID=0,resetButton=!1,speedIsZero=!1;
function moveDisk(a,b){if(a){if(intervalID&&(b=parseInt(document.getElementById("speed").value),0>=b))return clearInterval(intervalID),intervalID=0,!0;if(resetButton||moveIndex>=fromT.length)return clearInterval(intervalID),intervalID=0,resetButton&&(resetButton=!1,resetMove()),!0;var c=fromT[moveIndex],d=toT[moveIndex];moveIndex++}else{if(0>=moveIndex)return!0;moveIndex--;c=fromT[moveIndex];d=toT[moveIndex]}if(1>c||3<c||1>d||3<d)return clearInterval(intervalID),intervalID=0,alert("Tower number should be 1, 2, or 3; from="+
c+"to="+d),!1;if(c==d)return clearInterval(intervalID),intervalID=0,alert("Two Tower numbers are the same; from="+c+"to="+d),!1;var f=towers[d-1],e=towers[c-1],g=a?e.pop():f.pop();if("undefined"==typeof g)return clearInterval(intervalID),intervalID=0,alert("Cannot move disk from "+c+" to "+d),!1;if(1>g||g>ndisks)return clearInterval(intervalID),intervalID=0,alert("Invalid disk number : "+g),!1;a?e.push(g):f.push(g);drawDisks(!1);a?(g=e.pop(),f.push(g)):(g=f.pop(),e.push(g));drawPoles(!0);drawDisks(!0);
document.getElementById("nummove").innerHTML=moveIndex;if("X"==document.getElementById("trackmode").innerHTML)return 0<trackbx&&(drawCurve(!1,trackbx,trackby,trackex,trackey),trackbx=trackby=trackex=trackey=0),!0;if(0>=b||b>=trackMin){var g=b-trackGd,h=c+d-3,j=trackx1[h],h=trackx2[h],i=canvash-tbaseh-tbaseint-dh,k=i;a?(c>d&&(c=j,j=h,h=c),i-=(dh+dint)*e.length,k-=(dh+dint)*f.length):(d>c&&(c=j,j=h,h=c),i-=(dh+dint)*f.length,k-=(dh+dint)*e.length);0<b?drawTrack(g,j,i,h,k):drawTrack(0,j,i,h,k)}return!0}
function resetMove(){0<trackbx&&(drawCurve(!1,trackbx,trackby,trackex,trackey),trackbx=trackby=trackex=trackey=0);drawPoles(!1);drawDisks(!1);createTowers();drawTowers();moveIndex=document.getElementById("nummove").innerHTML=0}function hanoiReset(){intervalID?resetButton=!0:resetMove()}
function hanoiMove(a){var b=document.getElementById("hcpy");if(b){for(var c="ng Bo in Hy ok Mi ou".split(" "),d=0;d<c.length;d++)if(0>b.innerHTML.indexOf(c[d]))return;if(intervalID)alert("Currently Moving ...");else if(fromT.length!=toT.length)alert("Invalid move data");else if(1>fromT.length)alert("Nothing to move");else{if(a){if(moveIndex>=fromT.length){alert("Please Reset before Move");return}}else if(0>=moveIndex){alert("All disks are at tower 1");return}var f=document.getElementById("speed").value,
f=parseInt(f);moveDisk(a,f);1>f||(intervalID=setInterval(function(){moveDisk(!0,f)},f))}}}
function moveMode(){var a=document.getElementById("speed").value,a=parseInt(a);if(0<a){if(speedIsZero){speedIsZero=!1;var a=document.getElementById("prevbut"),b=document.getElementById("movbut");a.style.display="none";b.style.marginLeft="20px";b.innerHTML="Move";0<trackbx&&(drawCurve(!1,trackbx,trackby,trackex,trackey),trackbx=trackby=trackex=trackey=0)}}else speedIsZero||(speedIsZero=!0,a=document.getElementById("prevbut"),b=document.getElementById("movbut"),a.style.display="inline",b.style.marginLeft=
"0px",b.innerHTML="&#8594")}
function copyR(){var a=(new Date).getFullYear();2013<a&&(a="2013 - "+a);var b=document.createElement("p"),c=document.createElement("a");c.href="http://class.icc.skku.ac.kr/~min/program/license.html";c.target="_blank";c.id="hcpy";a="Copyright "+String.fromCharCode(169)+" "+a;a=document.createTextNode(a+" by Hyoung Bok Min");c.appendChild(a);a=document.createTextNode(", All rights reserved.");b.appendChild(c);b.appendChild(a);document.getElementById("wrapper").appendChild(b)}
function isIE8earlier(){var a=navigator.userAgent.match(/MSIE\s+[0-9]+\.[0-9]+/i);if(!a)return!1;a=a[0].match(/[0-9]+/);return 8<parseInt(a[0])?!1:!0}window.onload=function(){copyR();createTowers()&&drawTowers();moveIndex=0};
