// File name : hanoi_sol.js
// Solution of Tower of Hanoi in JavaScript
// Generated by "C:\Users\mjchung\Desktop\program_file(C)\testHW9\2017311583.Á¤ÇØÁø.HW9.c" on Tue Jun 12 19:00:26 2018
var ndisks = 4;   // number of disks
var to_tower = 3; // to-tower number
var fromT = [ 1, 1, 2, 1, 3, 3, 1, 1, 2, 2, 3, 2, 1, 1, 2 ];
var toT   = [ 2, 3, 3, 2, 1, 2, 2, 3, 3, 1, 1, 3, 2, 3, 3 ];
// End of Solution
